version: "3.8"

services:
  linkgroup:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: linkgroup:latest
    container_name: linkgroup
    volumes:
      - ./var:/var/www/linkgroup/var:rw
      - ./.env.local:/var/www/linkgroup/.env.local:rw
    tty: true
    labels:
      - traefik.http.routers.linkgroup.rule=Host(`linkgroup.melaine-gerard.fr`)
      - traefik.http.routers.linkgroup.tls=true
      - traefik.http.routers.linkgroup.tls.certresolver=lets-encrypt
      - traefik.port=80
      - "traefik.enable=true"
    networks:
      - local

networks:
  local:
    name: local
    external: true